---
abstract: 'console emphasis tool'
author:
  - 'Andreas Lund <floyd@atc.no>, C Hutchinson <taint@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.131560'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: cet
no_index:
  directory:
    - t
    - inc
requires:
  File::Spec: 0
  Term::ReadLine: 0
  perl: 5.008005
version: 2.02
